/** Mirrors the challenge document generated by the API (src/ai/ai.types.ts). */

export type ChallengeLevel = 'INTERN' | 'JUNIOR' | 'MID' | 'SENIOR';
export type ChallengeStatus = 'GENERATING' | 'READY' | 'FAILED';

export interface ChallengeRequirement {
  title: string;
  description: string;
  details: string[];
}

export interface ChallengeTechnologyGroup {
  category: string;
  items: { name: string; purpose: string }[];
}

export interface ChallengeGuideSection {
  title: string;
  description: string;
  items: string[];
}

export interface ChallengeContent {
  context: string[];
  functionalRequirements: ChallengeRequirement[];
  nonFunctionalRequirements: ChallengeRequirement[];
  technologies: ChallengeTechnologyGroup[];
  deliverables: string[];
  deadline: string;
  implementationGuide: ChallengeGuideSection[];
  evaluationCriteria: { title: string; description: string }[];
  folderStructure: string;
  closingNote: string;
}

export interface ChallengeSummary {
  id: string;
  level: ChallengeLevel;
  status: ChallengeStatus;
  title: string | null;
  projectName: string | null;
  industry: string | null;
  summary: string | null;
  public: boolean;
  regenerationsUsed: number;
  createdAt: string;
  stack: { slug: string; name: string };
  framework: { slug: string; name: string; language: string };
}

export interface ChallengeVersion {
  version: number;
  title: string;
  projectName: string;
  industry: string;
  summary: string;
  content: ChallengeContent;
  createdAt: string;
}

export interface ChallengeDetail extends ChallengeSummary {
  content: ChallengeContent | null;
  /** Only the owner gets the versions (and can act on the challenge). */
  isOwner: boolean;
  versions: ChallengeVersion[];
}

export interface Paginated<T> {
  items: T[];
  total: number;
  page: number;
  limit: number;
}

export interface Framework {
  id: string;
  slug: string;
  name: string;
  language: string;
}

export interface Stack {
  id: string;
  slug: string;
  name: string;
  frameworks: Framework[];
}
